apiVersion: v1
kind: Service
metadata:
  name: atm10
  namespace: default
  labels:
    app: atm10
spec:
  type: NodePort
  ports:
    - name: atm10
      port: 25565
      targetPort: 25565
      nodePort: 30065
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: 25575
      nodePort: 30075
      protocol: TCP
  selector:
    app: atm10
